# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OscilloscopeWidgetUI_v1_02.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OscilloscopeWidget(object):
    def setupUi(self, OscilloscopeWidget):
        OscilloscopeWidget.setObjectName("OscilloscopeWidget")
        OscilloscopeWidget.resize(1403, 537)
        self.gridLayout_3 = QtWidgets.QGridLayout(OscilloscopeWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(OscilloscopeWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.MeasurementLabel = QtWidgets.QLabel(self.groupBox_2)
        self.MeasurementLabel.setText("")
        self.MeasurementLabel.setObjectName("MeasurementLabel")
        self.gridLayout_4.addWidget(self.MeasurementLabel, 0, 0, 1, 1)
        self.Measurement_Immed = QtWidgets.QLabel(self.groupBox_2)
        self.Measurement_Immed.setText("")
        self.Measurement_Immed.setObjectName("Measurement_Immed")
        self.gridLayout_4.addWidget(self.Measurement_Immed, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(OscilloscopeWidget)
        self.frame.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ch1Label = QtWidgets.QLabel(self.frame)
        self.ch1Label.setEnabled(False)
        self.ch1Label.setStyleSheet("color: rgb(255, 255, 0);")
        self.ch1Label.setTextFormat(QtCore.Qt.AutoText)
        self.ch1Label.setObjectName("ch1Label")
        self.horizontalLayout_3.addWidget(self.ch1Label)
        self.ch1Y = QtWidgets.QLabel(self.frame)
        self.ch1Y.setStyleSheet("color: rgb(255, 255, 255);")
        self.ch1Y.setObjectName("ch1Y")
        self.horizontalLayout_3.addWidget(self.ch1Y)
        self.ch2Label = QtWidgets.QLabel(self.frame)
        self.ch2Label.setStyleSheet("color: rgb(36, 127, 13);")
        self.ch2Label.setTextFormat(QtCore.Qt.AutoText)
        self.ch2Label.setObjectName("ch2Label")
        self.horizontalLayout_3.addWidget(self.ch2Label)
        self.ch2Y = QtWidgets.QLabel(self.frame)
        self.ch2Y.setStyleSheet("color: rgb(255, 255, 255);")
        self.ch2Y.setObjectName("ch2Y")
        self.horizontalLayout_3.addWidget(self.ch2Y)
        self.timebase = QtWidgets.QLabel(self.frame)
        self.timebase.setEnabled(False)
        self.timebase.setStyleSheet("color: rgb(255, 255, 255);")
        self.timebase.setObjectName("timebase")
        self.horizontalLayout_3.addWidget(self.timebase)
        self.verticalLayout.addWidget(self.frame)
        self.widget = QtWidgets.QWidget(OscilloscopeWidget)
        self.widget.setMinimumSize(QtCore.QSize(400, 300))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.buttonLayout.setObjectName("buttonLayout")
        self.pushButton_Ch1 = QtWidgets.QPushButton(OscilloscopeWidget)
        self.pushButton_Ch1.setCheckable(True)
        self.pushButton_Ch1.setChecked(True)
        self.pushButton_Ch1.setObjectName("pushButton_Ch1")
        self.buttonLayout.addWidget(self.pushButton_Ch1)
        self.pushButton_Ch2 = QtWidgets.QPushButton(OscilloscopeWidget)
        self.pushButton_Ch2.setCheckable(True)
        self.pushButton_Ch2.setChecked(False)
        self.pushButton_Ch2.setObjectName("pushButton_Ch2")
        self.buttonLayout.addWidget(self.pushButton_Ch2)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 5, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.TriggerLevelText = QtWidgets.QDoubleSpinBox(OscilloscopeWidget)
        self.TriggerLevelText.setMinimum(-99.99)
        self.TriggerLevelText.setObjectName("TriggerLevelText")
        self.verticalLayout_5.addWidget(self.TriggerLevelText)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.TriggerLevelScroll = QtWidgets.QSlider(OscilloscopeWidget)
        self.TriggerLevelScroll.setEnabled(True)
        self.TriggerLevelScroll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TriggerLevelScroll.setMaximum(1000)
        self.TriggerLevelScroll.setSingleStep(1)
        self.TriggerLevelScroll.setProperty("value", 500)
        self.TriggerLevelScroll.setOrientation(QtCore.Qt.Vertical)
        self.TriggerLevelScroll.setObjectName("TriggerLevelScroll")
        self.horizontalLayout_10.addWidget(self.TriggerLevelScroll)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.CH1_VoltsScale_Val = QtWidgets.QLCDNumber(OscilloscopeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CH1_VoltsScale_Val.sizePolicy().hasHeightForWidth())
        self.CH1_VoltsScale_Val.setSizePolicy(sizePolicy)
        self.CH1_VoltsScale_Val.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.CH1_VoltsScale_Val.setProperty("value", 1.0)
        self.CH1_VoltsScale_Val.setObjectName("CH1_VoltsScale_Val")
        self.verticalLayout_7.addWidget(self.CH1_VoltsScale_Val)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CH1_VoltsScaleDecrease = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH1_VoltsScaleDecrease.setObjectName("CH1_VoltsScaleDecrease")
        self.horizontalLayout_7.addWidget(self.CH1_VoltsScaleDecrease)
        self.CH1_VoltsScaleIncrease = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH1_VoltsScaleIncrease.setObjectName("CH1_VoltsScaleIncrease")
        self.horizontalLayout_7.addWidget(self.CH1_VoltsScaleIncrease)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.CH2_VoltsScale_Val = QtWidgets.QLCDNumber(OscilloscopeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CH2_VoltsScale_Val.sizePolicy().hasHeightForWidth())
        self.CH2_VoltsScale_Val.setSizePolicy(sizePolicy)
        self.CH2_VoltsScale_Val.setProperty("value", 1.0)
        self.CH2_VoltsScale_Val.setObjectName("CH2_VoltsScale_Val")
        self.verticalLayout_9.addWidget(self.CH2_VoltsScale_Val)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.CH2_VoltsScaleDecrease = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH2_VoltsScaleDecrease.setObjectName("CH2_VoltsScaleDecrease")
        self.horizontalLayout_12.addWidget(self.CH2_VoltsScaleDecrease)
        self.CH2_VoltsScaleIncrease = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH2_VoltsScaleIncrease.setObjectName("CH2_VoltsScaleIncrease")
        self.horizontalLayout_12.addWidget(self.CH2_VoltsScaleIncrease)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.HorizontalScale_Val = QtWidgets.QLCDNumber(OscilloscopeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HorizontalScale_Val.sizePolicy().hasHeightForWidth())
        self.HorizontalScale_Val.setSizePolicy(sizePolicy)
        self.HorizontalScale_Val.setProperty("value", 1e-05)
        self.HorizontalScale_Val.setObjectName("HorizontalScale_Val")
        self.verticalLayout_4.addWidget(self.HorizontalScale_Val)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.HorizontalScaleDecrease = QtWidgets.QPushButton(OscilloscopeWidget)
        self.HorizontalScaleDecrease.setObjectName("HorizontalScaleDecrease")
        self.horizontalLayout_6.addWidget(self.HorizontalScaleDecrease)
        self.HorizontalScaleIncrease = QtWidgets.QPushButton(OscilloscopeWidget)
        self.HorizontalScaleIncrease.setObjectName("HorizontalScaleIncrease")
        self.horizontalLayout_6.addWidget(self.HorizontalScaleIncrease)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.CH1_AC = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH1_AC.setObjectName("CH1_AC")
        self.horizontalLayout_9.addWidget(self.CH1_AC)
        self.CH1_DC = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH1_DC.setObjectName("CH1_DC")
        self.horizontalLayout_9.addWidget(self.CH1_DC)
        self.CH1_GND = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH1_GND.setObjectName("CH1_GND")
        self.horizontalLayout_9.addWidget(self.CH1_GND)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.CH2_AC = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH2_AC.setObjectName("CH2_AC")
        self.horizontalLayout_8.addWidget(self.CH2_AC)
        self.CH2_DC = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH2_DC.setObjectName("CH2_DC")
        self.horizontalLayout_8.addWidget(self.CH2_DC)
        self.CH2_GND = QtWidgets.QPushButton(OscilloscopeWidget)
        self.CH2_GND.setObjectName("CH2_GND")
        self.horizontalLayout_8.addWidget(self.CH2_GND)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.label_5 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TriggerLevelMul = QtWidgets.QLCDNumber(OscilloscopeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerLevelMul.sizePolicy().hasHeightForWidth())
        self.TriggerLevelMul.setSizePolicy(sizePolicy)
        self.TriggerLevelMul.setProperty("value", 1.0)
        self.TriggerLevelMul.setObjectName("TriggerLevelMul")
        self.verticalLayout_6.addWidget(self.TriggerLevelMul)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Trigger_Decrease = QtWidgets.QPushButton(OscilloscopeWidget)
        self.Trigger_Decrease.setObjectName("Trigger_Decrease")
        self.horizontalLayout_2.addWidget(self.Trigger_Decrease)
        self.Trigger_Increase = QtWidgets.QPushButton(OscilloscopeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Trigger_Increase.sizePolicy().hasHeightForWidth())
        self.Trigger_Increase.setSizePolicy(sizePolicy)
        self.Trigger_Increase.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Trigger_Increase.setObjectName("Trigger_Increase")
        self.horizontalLayout_2.addWidget(self.Trigger_Increase)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.SetTriggerLevel = QtWidgets.QPushButton(OscilloscopeWidget)
        self.SetTriggerLevel.setObjectName("SetTriggerLevel")
        self.verticalLayout_5.addWidget(self.SetTriggerLevel)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 2, 5, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.updateIntervalSpinBox = QtWidgets.QDoubleSpinBox(OscilloscopeWidget)
        self.updateIntervalSpinBox.setMinimum(4.0)
        self.updateIntervalSpinBox.setMaximum(100.0)
        self.updateIntervalSpinBox.setSingleStep(0.5)
        self.updateIntervalSpinBox.setObjectName("updateIntervalSpinBox")
        self.gridLayout_2.addWidget(self.updateIntervalSpinBox, 1, 2, 1, 1)
        self.updateButton = QtWidgets.QPushButton(OscilloscopeWidget)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout_2.addWidget(self.updateButton, 0, 1, 2, 1)
        self.label = QtWidgets.QLabel(OscilloscopeWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.autoUpdateButton = QtWidgets.QPushButton(OscilloscopeWidget)
        self.autoUpdateButton.setCheckable(True)
        self.autoUpdateButton.setObjectName("autoUpdateButton")
        self.gridLayout_2.addWidget(self.autoUpdateButton, 0, 3, 2, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 4, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(OscilloscopeWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.triggerSourceComboBox = QtWidgets.QComboBox(OscilloscopeWidget)
        self.triggerSourceComboBox.setObjectName("triggerSourceComboBox")
        self.triggerSourceComboBox.addItem("")
        self.triggerSourceComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.triggerSourceComboBox)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 3, 1, 1)
        self.triggerForceButton = QtWidgets.QPushButton(OscilloscopeWidget)
        self.triggerForceButton.setObjectName("triggerForceButton")
        self.gridLayout.addWidget(self.triggerForceButton, 1, 2, 1, 1)
        self.runStopButton = QtWidgets.QPushButton(OscilloscopeWidget)
        self.runStopButton.setCheckable(True)
        self.runStopButton.setChecked(False)
        self.runStopButton.setObjectName("runStopButton")
        self.gridLayout.addWidget(self.runStopButton, 0, 0, 1, 1)
        self.runStopStatus = QtWidgets.QLabel(OscilloscopeWidget)
        self.runStopStatus.setObjectName("runStopStatus")
        self.gridLayout.addWidget(self.runStopStatus, 0, 1, 1, 1)
        self.AutoSet_Button = QtWidgets.QPushButton(OscilloscopeWidget)
        self.AutoSet_Button.setObjectName("AutoSet_Button")
        self.gridLayout.addWidget(self.AutoSet_Button, 1, 0, 1, 1)
        self.singleButton = QtWidgets.QPushButton(OscilloscopeWidget)
        self.singleButton.setCheckable(True)
        self.singleButton.setObjectName("singleButton")
        self.gridLayout.addWidget(self.singleButton, 1, 1, 1, 1)
        self.LOG_START = QtWidgets.QPushButton(OscilloscopeWidget)
        self.LOG_START.setObjectName("LOG_START")
        self.gridLayout.addWidget(self.LOG_START, 0, 2, 1, 1)
        self.Log_State = QtWidgets.QLabel(OscilloscopeWidget)
        self.Log_State.setObjectName("Log_State")
        self.gridLayout.addWidget(self.Log_State, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(OscilloscopeWidget)
        self.updateButton.clicked.connect(OscilloscopeWidget.updatePlot)
        self.runStopButton.clicked['bool'].connect(OscilloscopeWidget.runStop)
        self.triggerForceButton.clicked.connect(OscilloscopeWidget.triggerForced)
        self.triggerSourceComboBox.activated['QString'].connect(OscilloscopeWidget.triggerSourceChanged)
        self.singleButton.clicked.connect(OscilloscopeWidget.single)
        self.autoUpdateButton.clicked['bool'].connect(OscilloscopeWidget.autoUpdate)
        self.SetTriggerLevel.clicked.connect(OscilloscopeWidget.set_triggerLevel)
        self.TriggerLevelText.valueChanged['double'].connect(OscilloscopeWidget.triggerLevelChanged_TextBox)
        self.TriggerLevelScroll.valueChanged['int'].connect(OscilloscopeWidget.triggerLevelChanged_Scroll)
        self.Trigger_Increase.clicked.connect(OscilloscopeWidget.ScrollTriggerMulInc)
        self.Trigger_Decrease.clicked.connect(OscilloscopeWidget.ScrollTriggerMulDec)
        self.pushButton_Ch1.clicked.connect(OscilloscopeWidget.set_Ch1)
        self.pushButton_Ch2.clicked.connect(OscilloscopeWidget.set_Ch2)
        self.AutoSet_Button.clicked.connect(OscilloscopeWidget.AutoSet)
        self.HorizontalScaleDecrease.clicked.connect(OscilloscopeWidget.HorizontalScaleDecrease)
        self.HorizontalScaleIncrease.clicked.connect(OscilloscopeWidget.HorizontalScaleIncrease)
        self.CH1_AC.clicked.connect(OscilloscopeWidget.set_CH1_AC)
        self.CH1_DC.clicked.connect(OscilloscopeWidget.set_CH1_DC)
        self.CH1_GND.clicked.connect(OscilloscopeWidget.set_CH1_GND)
        self.CH2_AC.clicked.connect(OscilloscopeWidget.set_CH2_AC)
        self.CH2_DC.clicked.connect(OscilloscopeWidget.set_CH2_DC)
        self.CH2_GND.clicked.connect(OscilloscopeWidget.set_CH2_GND)
        self.LOG_START.clicked.connect(OscilloscopeWidget.Log_Start)
        self.CH1_VoltsScaleDecrease.clicked.connect(OscilloscopeWidget.CH1_VoltsScaleDecrease)
        self.CH1_VoltsScaleIncrease.clicked.connect(OscilloscopeWidget.CH1_VoltsScaleIncrease)
        self.CH2_VoltsScaleDecrease.clicked.connect(OscilloscopeWidget.CH2_VoltsScaleDecrease)
        self.CH2_VoltsScaleIncrease.clicked.connect(OscilloscopeWidget.CH2_VoltsScaleIncrease)
        QtCore.QMetaObject.connectSlotsByName(OscilloscopeWidget)

    def retranslateUi(self, OscilloscopeWidget):
        _translate = QtCore.QCoreApplication.translate
        OscilloscopeWidget.setWindowTitle(_translate("OscilloscopeWidget", "Oscilloscope"))
        self.groupBox_2.setTitle(_translate("OscilloscopeWidget", "Measurements"))
        self.ch1Label.setText(_translate("OscilloscopeWidget", "1"))
        self.ch1Y.setText(_translate("OscilloscopeWidget", "ch1"))
        self.ch2Label.setText(_translate("OscilloscopeWidget", "2"))
        self.ch2Y.setText(_translate("OscilloscopeWidget", "ch2"))
        self.timebase.setText(_translate("OscilloscopeWidget", "timebase"))
        self.pushButton_Ch1.setText(_translate("OscilloscopeWidget", "Ch1"))
        self.pushButton_Ch2.setText(_translate("OscilloscopeWidget", "Ch2"))
        self.label_2.setText(_translate("OscilloscopeWidget", "TriggerLevel"))
        self.label_6.setText(_translate("OscilloscopeWidget", "CH1 Volts Scale"))
        self.CH1_VoltsScaleDecrease.setText(_translate("OscilloscopeWidget", "Decrease"))
        self.CH1_VoltsScaleIncrease.setText(_translate("OscilloscopeWidget", "Increase"))
        self.label_9.setText(_translate("OscilloscopeWidget", "CH2 Volts Scale"))
        self.CH2_VoltsScaleDecrease.setText(_translate("OscilloscopeWidget", "Decrease"))
        self.CH2_VoltsScaleIncrease.setText(_translate("OscilloscopeWidget", "Increase"))
        self.label_3.setText(_translate("OscilloscopeWidget", "Horizontal Scale"))
        self.HorizontalScaleDecrease.setText(_translate("OscilloscopeWidget", "Decrease"))
        self.HorizontalScaleIncrease.setText(_translate("OscilloscopeWidget", "Increase"))
        self.label_8.setText(_translate("OscilloscopeWidget", "CH1"))
        self.CH1_AC.setText(_translate("OscilloscopeWidget", "AC"))
        self.CH1_DC.setText(_translate("OscilloscopeWidget", "DC"))
        self.CH1_GND.setText(_translate("OscilloscopeWidget", "GND"))
        self.label_7.setText(_translate("OscilloscopeWidget", "CH2"))
        self.CH2_AC.setText(_translate("OscilloscopeWidget", "AC"))
        self.CH2_DC.setText(_translate("OscilloscopeWidget", "DC"))
        self.CH2_GND.setText(_translate("OscilloscopeWidget", "GND"))
        self.label_5.setText(_translate("OscilloscopeWidget", "ScrollTriggerMultiply"))
        self.Trigger_Decrease.setText(_translate("OscilloscopeWidget", "Decrease"))
        self.Trigger_Increase.setText(_translate("OscilloscopeWidget", "Increase"))
        self.SetTriggerLevel.setText(_translate("OscilloscopeWidget", "SetTrigger"))
        self.updateButton.setText(_translate("OscilloscopeWidget", "Update"))
        self.label.setText(_translate("OscilloscopeWidget", "Interval (s)"))
        self.autoUpdateButton.setText(_translate("OscilloscopeWidget", "Auto\n"
"update"))
        self.label_4.setText(_translate("OscilloscopeWidget", "Source"))
        self.triggerSourceComboBox.setItemText(0, _translate("OscilloscopeWidget", "CH1"))
        self.triggerSourceComboBox.setItemText(1, _translate("OscilloscopeWidget", "CH2"))
        self.triggerForceButton.setText(_translate("OscilloscopeWidget", "Trigger\n"
"Force"))
        self.runStopButton.setText(_translate("OscilloscopeWidget", "RUN/\n"
"STOP"))
        self.runStopStatus.setText(_translate("OscilloscopeWidget", "STOP"))
        self.AutoSet_Button.setText(_translate("OscilloscopeWidget", "AutoSet"))
        self.singleButton.setText(_translate("OscilloscopeWidget", "Single"))
        self.LOG_START.setText(_translate("OscilloscopeWidget", "LOG\n"
"START"))
        self.Log_State.setText(_translate("OscilloscopeWidget", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OscilloscopeWidget = QtWidgets.QWidget()
    ui = Ui_OscilloscopeWidget()
    ui.setupUi(OscilloscopeWidget)
    OscilloscopeWidget.show()
    sys.exit(app.exec_())

